spring:
  application:
    name: jooq
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: 'jdbc:h2:file:./build/data/testdb;MODE=PostgreSQL;AUTO_SERVER=TRUE;'
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8009
